import type { Collection } from "./types"

export const mockCollections: Collection[] = [
  {
    id: 1,
    name: "Cosmic Creatures",
    description:
      "10,000 unique cosmic beings with built-in AMM liquidity. Each purchase increases floor price via bonding curve mechanics.",
    image: "/placeholder.svg?height=300&width=300&text=Cosmic+Creatures",
    creator: "ArtistDAO",
    price: "0.05 ETH",
    minted: 2847,
    total: 10000,
    mintPhase: "live",
    chain: "ethereum",
    hasLiquidity: true,
    liquidityPercent: 15,
    royalties: 5,
    mintType: "Public",
    bondingCurve: {
      priceIncrease: 2.5,
    },
  },
  {
    id: 2,
    name: "Digital Dreamscapes",
    description:
      "Surreal digital landscapes that evolve over time. Features dynamic NFT-AMM integration with real-time price discovery.",
    image: "/placeholder.svg?height=300&width=300&text=Digital+Dreamscapes",
    creator: "DreamLab",
    price: "0.08 ETH",
    minted: 0,
    total: 5000,
    mintPhase: "upcoming",
    chain: "ethereum",
    hasLiquidity: true,
    liquidityPercent: 20,
    royalties: 7.5,
    mintType: "Whitelist",
    bondingCurve: {
      priceIncrease: 3,
    },
  },
  {
    id: 3,
    name: "Pixel Warriors",
    description:
      "8-bit style warriors ready for battle. Traditional mint without AMM integration but with strong community backing.",
    image: "/placeholder.svg?height=300&width=300&text=Pixel+Warriors",
    creator: "GameStudio",
    price: "0.03 ETH",
    minted: 1234,
    total: 8888,
    mintPhase: "whitelist",
    chain: "polygon",
    hasLiquidity: false,
    liquidityPercent: 0,
    royalties: 2.5,
    mintType: "Whitelist",
  },
  {
    id: 4,
    name: "Neon Nights",
    description:
      "Cyberpunk-inspired collection with instant trading capabilities. Advanced bonding curve ensures price stability.",
    image: "/placeholder.svg?height=300&width=300&text=Neon+Nights",
    creator: "CyberArt",
    price: "0.12 ETH",
    minted: 4567,
    total: 7777,
    mintPhase: "trading",
    chain: "arbitrum",
    hasLiquidity: true,
    liquidityPercent: 25,
    royalties: 6,
    mintType: "Public",
    bondingCurve: {
      priceIncrease: 1.8,
    },
  },
  {
    id: 5,
    name: "Abstract Minds",
    description:
      "AI-generated abstract art pieces. Each NFT is unique and backed by algorithmic liquidity pools for instant trading.",
    image: "/placeholder.svg?height=300&width=300&text=Abstract+Minds",
    creator: "AI_Collective",
    price: "0.06 ETH",
    minted: 3456,
    total: 6666,
    mintPhase: "live",
    chain: "ethereum",
    hasLiquidity: true,
    liquidityPercent: 18,
    royalties: 4,
    mintType: "Public",
    bondingCurve: {
      priceIncrease: 2.2,
    },
  },
  {
    id: 6,
    name: "Ocean Depths",
    description:
      "Underwater world exploration NFTs. Deep sea creatures with mysterious powers and built-in trading mechanisms.",
    image: "/placeholder.svg?height=300&width=300&text=Ocean+Depths",
    creator: "AquaVerse",
    price: "0.04 ETH",
    minted: 2100,
    total: 9999,
    mintPhase: "whitelist",
    chain: "polygon",
    hasLiquidity: true,
    liquidityPercent: 12,
    royalties: 3.5,
    mintType: "Whitelist",
    bondingCurve: {
      priceIncrease: 1.5,
    },
  },
]
