import type { Collection } from "./types"

export const mockCollections: Collection[] = [
  {
    id: "insiders",
    name: "INSIDERS",
    description:
      "What if you saw what INSIDERS were doing before headlines broke? INS is a data-driven token tracking high-impact trades by politicians, corporate execs, and crypto whales. Built on Base, $INS bridges TradFi and DeFi, providing real-time tools for traders seeking an edge once reserved for elites. Grab your edge. Trade with insight. Be an INSIDER.",
    image: "/placeholder.svg?height=400&width=400&text=INSIDERS",
    creator: "InsiderTeam",
    price: "0.01 ETH",
    minted: 6420,
    total: 10000,
    mintPhase: "live",
    chain: "Base",
    royalties: 5,
    mintType: "Public",
    hasLiquidity: true,
    liquidityPercent: 18,
    bondingCurve: {
      priceIncrease: 15,
    },
    tokenInfo: {
      address: "0x889266B3DAdd70F23B95095e20e1BE73beD3bED",
      name: "INSIDERS",
      symbol: "INS",
      decimals: 18,
      totalSupply: "1,500,000,000",
    },
  },
  {
    id: "cyber-punks",
    name: "Cyber Punks Genesis",
    description:
      "Enter the neon-lit streets of Neo Tokyo where digital rebels fight against corporate tyranny. Each Cyber Punk is a unique warrior in the blockchain revolution, equipped with cybernetic enhancements and street-smart attitude. These aren't just NFTs - they're your identity in the metaverse uprising.",
    image: "/placeholder.svg?height=400&width=400&text=CyberPunks",
    creator: "NeoTokyo",
    price: "0.08 ETH",
    minted: 2847,
    total: 5000,
    mintPhase: "whitelist",
    chain: "Ethereum",
    royalties: 7.5,
    mintType: "Whitelist",
    hasLiquidity: false,
    liquidityPercent: 0,
    tokenInfo: {
      address: "0x123456789abcdef123456789abcdef123456789a",
      name: "Cyber Punks Genesis",
      symbol: "CPG",
      decimals: 18,
      totalSupply: "5,000",
    },
  },
  {
    id: "digital-dreamscapes",
    name: "Digital Dreamscapes",
    description:
      "Journey through impossible worlds where reality bends to imagination. These AI-generated landscapes evolve over time, creating living artworks that change based on market conditions, holder interactions, and cosmic events. Own a piece of the digital unconscious.",
    image: "/placeholder.svg?height=400&width=400&text=Dreamscapes",
    creator: "DreamLab",
    price: "0.05 ETH",
    minted: 1203,
    total: 3333,
    mintPhase: "upcoming",
    chain: "Polygon",
    royalties: 10,
    mintType: "Dutch Auction",
    hasLiquidity: true,
    liquidityPercent: 25,
    bondingCurve: {
      priceIncrease: 8,
    },
    tokenInfo: {
      address: "0xabcdef123456789abcdef123456789abcdef1234",
      name: "Digital Dreamscapes",
      symbol: "DREAM",
      decimals: 18,
      totalSupply: "3,333",
    },
  },
  {
    id: "quantum-beings",
    name: "Quantum Beings",
    description:
      "Interdimensional entities that exist across multiple realities simultaneously. Each Quantum Being possesses unique properties that affect their rarity and power within the ecosystem. Harness quantum mechanics to unlock hidden utilities and cross-dimensional trading opportunities.",
    image: "/placeholder.svg?height=400&width=400&text=Quantum",
    creator: "QuantumLabs",
    price: "0.12 ETH",
    minted: 4567,
    total: 7777,
    mintPhase: "trading",
    chain: "Arbitrum",
    royalties: 6,
    mintType: "Bonding Curve",
    hasLiquidity: true,
    liquidityPercent: 42,
    bondingCurve: {
      priceIncrease: 22,
    },
    tokenInfo: {
      address: "0x987654321fedcba987654321fedcba9876543210",
      name: "Quantum Beings",
      symbol: "QUANTUM",
      decimals: 18,
      totalSupply: "7,777",
    },
  },
  {
    id: "neon-samurai",
    name: "Neon Samurai",
    description:
      "Ancient honor meets futuristic warfare in this collection of cybernetic warriors. Each Neon Samurai carries the spirit of bushido into the digital age, wielding plasma katanas and neural interfaces. Join the clan and uphold the code in the neon-soaked battlefields of tomorrow.",
    image: "/placeholder.svg?height=400&width=400&text=Samurai",
    creator: "CyberDojo",
    price: "0.15 ETH",
    minted: 892,
    total: 2500,
    mintPhase: "live",
    chain: "Ethereum",
    royalties: 8,
    mintType: "Fixed Price",
    hasLiquidity: false,
    liquidityPercent: 0,
    tokenInfo: {
      address: "0xfedcba9876543210fedcba9876543210fedcba98",
      name: "Neon Samurai",
      symbol: "SAMURAI",
      decimals: 18,
      totalSupply: "2,500",
    },
  },
  {
    id: "mystic-crystals",
    name: "Mystic Crystals",
    description:
      "Discover ancient artifacts imbued with magical properties from forgotten realms. Each crystal resonates with elemental forces and grants its holder mystical abilities within the ecosystem. Combine crystals to unlock powerful spells and rare transformations in this enchanted collection.",
    image: "/placeholder.svg?height=400&width=400&text=Crystals",
    creator: "MysticRealm",
    price: "0.06 ETH",
    minted: 3456,
    total: 6000,
    mintPhase: "whitelist",
    chain: "Base",
    royalties: 5.5,
    mintType: "Whitelist",
    hasLiquidity: true,
    liquidityPercent: 15,
    bondingCurve: {
      priceIncrease: 12,
    },
    tokenInfo: {
      address: "0x456789abcdef123456789abcdef123456789abcde",
      name: "Mystic Crystals",
      symbol: "CRYSTAL",
      decimals: 18,
      totalSupply: "6,000",
    },
  },
]
