import type { Collection } from "./types"

export const mockCollections: Collection[] = [
  {
    id: 1,
    name: "Cosmic Creatures",
    description:
      "10,000 unique cosmic beings with built-in AMM liquidity. Each purchase increases floor price via bonding curve mechanics.",
    image: "/placeholder.svg?height=400&width=400&text=Cosmic+Creatures&bg=1a1a2e&color=16213e",
    mintPhase: "live",
    price: "0.25 ETH",
    minted: 2847,
    total: 10000,
    chain: "ethereum",
    creator: "CosmicDAO",
    category: "Art",
    hasLiquidity: true,
    liquidityPercent: 15,
    royalties: 5,
    mintType: "Fixed",
    bondingCurve: {
      priceIncrease: 2.5,
      currentMultiplier: 1.2,
    },
  },
  {
    id: 2,
    name: "Digital Dreamscapes",
    description:
      "Surreal digital landscapes with instant trading post-mint. Features tiered pricing and automatic liquidity provision.",
    image: "/placeholder.svg?height=400&width=400&text=Digital+Dreams&bg=0f3460&color=16537e",
    mintPhase: "trading",
    price: "0.18 ETH",
    minted: 8888,
    total: 8888,
    chain: "polygon",
    creator: "DreamLab",
    category: "Art",
    hasLiquidity: true,
    liquidityPercent: 20,
    royalties: 7.5,
    mintType: "Tiered",
    bondingCurve: {
      priceIncrease: 3.0,
      currentMultiplier: 1.8,
    },
  },
  {
    id: 3,
    name: "Pixel Warriors",
    description:
      "8-bit warriors with memecoin-style trading mechanics. Sold out mint now trading on NFT-AMM with bonding curves.",
    image: "/placeholder.svg?height=400&width=400&text=Pixel+Warriors&bg=533483&color=7209b7",
    mintPhase: "trading",
    price: "0.12 ETH",
    minted: 5000,
    total: 5000,
    chain: "ethereum",
    creator: "PixelStudio",
    category: "Gaming",
    hasLiquidity: true,
    liquidityPercent: 25,
    royalties: 5,
    mintType: "Fixed",
    bondingCurve: {
      priceIncrease: 4.0,
      currentMultiplier: 2.1,
    },
  },
  {
    id: 4,
    name: "Neon Nights",
    description:
      "Cyberpunk cityscapes with whitelist phase active. Early supporters get discounted pricing before public mint.",
    image: "/placeholder.svg?height=400&width=400&text=Neon+Nights&bg=2d1b69&color=8b5cf6",
    mintPhase: "whitelist",
    price: "0.08 ETH",
    minted: 1234,
    total: 7777,
    chain: "arbitrum",
    creator: "NeonArt",
    category: "Art",
    hasLiquidity: true,
    liquidityPercent: 12,
    royalties: 6,
    mintType: "Tiered",
  },
  {
    id: 5,
    name: "Space Explorers",
    description:
      "Upcoming collection with innovative free mint + manual liquidity model. Community-driven pricing discovery.",
    image: "/placeholder.svg?height=400&width=400&text=Space+Explorers&bg=1e3a8a&color=3b82f6",
    mintPhase: "upcoming",
    price: "Free Mint",
    minted: 0,
    total: 6666,
    chain: "ethereum",
    creator: "SpaceDAO",
    category: "Sci-Fi",
    hasLiquidity: false,
    liquidityPercent: 0,
    royalties: 5,
    mintType: "Free",
  },
  {
    id: 6,
    name: "Mystic Forests",
    description:
      "Enchanted forests with dynamic liquidity pools. Features algorithmic floor pricing and instant trading capabilities.",
    image: "/placeholder.svg?height=400&width=400&text=Mystic+Forests&bg=166534&color=22c55e",
    mintPhase: "live",
    price: "0.22 ETH",
    minted: 3456,
    total: 9999,
    chain: "polygon",
    creator: "ForestKeepers",
    category: "Fantasy",
    hasLiquidity: true,
    liquidityPercent: 18,
    royalties: 7,
    mintType: "Fixed",
    bondingCurve: {
      priceIncrease: 1.8,
      currentMultiplier: 1.1,
    },
  },
  {
    id: 7,
    name: "Cyber Punks",
    description:
      "High-value cyberpunk collection with premium AMM integration. Features advanced bonding curve mechanics.",
    image: "/placeholder.svg?height=400&width=400&text=Cyber+Punks&bg=dc2626&color=ef4444",
    mintPhase: "live",
    price: "0.35 ETH",
    minted: 2100,
    total: 4444,
    chain: "ethereum",
    creator: "CyberCollective",
    category: "Cyberpunk",
    hasLiquidity: true,
    liquidityPercent: 30,
    royalties: 10,
    mintType: "Tiered",
    bondingCurve: {
      priceIncrease: 5.0,
      currentMultiplier: 1.4,
    },
  },
  {
    id: 8,
    name: "Ocean Depths",
    description: "Deep sea creatures with massive supply and low entry price. Perfect for testing AMM scalability.",
    image: "/placeholder.svg?height=400&width=400&text=Ocean+Depths&bg=0891b2&color=06b6d4",
    mintPhase: "live",
    price: "0.09 ETH",
    minted: 6789,
    total: 12000,
    chain: "polygon",
    creator: "AquaArt",
    category: "Nature",
    hasLiquidity: true,
    liquidityPercent: 10,
    royalties: 4,
    mintType: "Fixed",
    bondingCurve: {
      priceIncrease: 1.2,
      currentMultiplier: 1.05,
    },
  },
  {
    id: 9,
    name: "Robot Revolution",
    description:
      "AI-themed collection launching soon with innovative liquidity mechanisms and community governance features.",
    image: "/placeholder.svg?height=400&width=400&text=Robot+Revolution&bg=374151&color=6b7280",
    mintPhase: "upcoming",
    price: "0.28 ETH",
    minted: 0,
    total: 8000,
    chain: "ethereum",
    creator: "RoboDAO",
    category: "Sci-Fi",
    hasLiquidity: true,
    liquidityPercent: 22,
    royalties: 6,
    mintType: "Tiered",
  },
  {
    id: 10,
    name: "Ancient Legends",
    description: "Mythical beings now trading on AMM with established liquidity. Proven bonding curve performance.",
    image: "/placeholder.svg?height=400&width=400&text=Ancient+Legends&bg=92400e&color=f59e0b",
    mintPhase: "trading",
    price: "0.31 ETH",
    minted: 7500,
    total: 7500,
    chain: "arbitrum",
    creator: "LegendKeepers",
    category: "Mythology",
    hasLiquidity: true,
    liquidityPercent: 28,
    royalties: 8,
    mintType: "Fixed",
    bondingCurve: {
      priceIncrease: 3.5,
      currentMultiplier: 2.3,
    },
  },
]
